apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: z-postgres-operator
 
generatorOptions:
  disableNameSuffixHash: true
 
secretGenerator: 
 
resources:
  - ./codes/deployment.yml
  - ./codes/service.yml