# Dynamic Provisioning（nfs driver）
apiVersion: storage.k8s.io/v1
kind: StorageClass
# メタデータ
metadata:
  name: sc-nas-psqldp
provisioner: smb.csi.k8s.io
parameters:
  source: //192.168.166.222/s90_SoftLib/Saigai/Compo/psqlDP
  # subDir: 
  csi.storage.k8s.io/provisioner-secret-namespace: "default"
  csi.storage.k8s.io/provisioner-secret-name: "secret-nas-ryu"
  csi.storage.k8s.io/node-stage-secret-namespace: "default"
  csi.storage.k8s.io/node-stage-secret-name: "secret-nas-ryu"
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0750
  - file_mode=0750
  - uid=1001
  - gid=1001
  - hard
  - vers=2.0