apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb
 
generatorOptions:
  disableNameSuffixHash: true
 
secretGenerator: 
 
resources:
  - ./codes/l2.yml
  - ./codes/pool.yml