apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
 
generatorOptions:
  disableNameSuffixHash: true
 
secretGenerator: 
 
resources:
  - ./codes/secret-nas-ryu.yml
  - ./codes/sc-smb-nas-dp.yml
  - ./codes/sc-smb-nas-ansiblepostgres.yml
  - ./codes/sc-smb-nas-ansibleproject.yml
  - ./codes/sc-nas-psqldp.yml