# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   annotations:
#     meta.helm.sh/release-name: gitlab-helm
#     meta.helm.sh/release-namespace: gitlab-helm
#   finalizers:
#     - kubernetes.io/pvc-protection
#   labels:
#     app: minio
#     app.kubernetes.io/managed-by: Helm
#     chart: minio-0.4.3
#     heritage: Helm
#     release: gitlab-helm
#   name: gitlab-helm-minio
#   namespace: gitlab-helm
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi
#   volumeMode: Filesystem
#   storageClassName: ceph-fs

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    meta.helm.sh/release-name: gitlab-helm
    meta.helm.sh/release-namespace: gitlab-helm
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app: prometheus
    app.kubernetes.io/managed-by: Helm
    chart: prometheus-15.0.4
    component: server
    heritage: Helm
    release: gitlab-helm
  name: gitlab-helm-prometheus-server
  namespace: gitlab-helm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem
  storageClassName: ceph-fs

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app: redis
    component: master
    heritage: Helm
    release: gitlab-helm
    role: master
  name: redis-data-gitlab-helm-redis-master-0
  namespace: gitlab-helm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem
  storageClassName: ceph-fs

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app: gitaly
    release: gitlab-helm
  name: repo-data-gitlab-helm-gitaly-0
  namespace: gitlab-helm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
  storageClassName: ceph-fs
