---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-awx-postgres
spec:
  storageClassName: pv-awx-postgres
  mountOptions:
    - dir_mode=0750
    - file_mode=0750
    - uid=999
    - gid=999
    - vers=2.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: pv-awx-postgres  # make sure it's a unique id in the cluster
    volumeAttributes:
      source: "//192.168.166.11/kubernetesVolumes"
      subDir: "swagger"
    nodeStageSecretRef:
      namespace: default
      name: "smb-ryu-cred"
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 2Gi
 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-awx-projects
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 2Gi
  storageClassName: sc-pv-awx-projects
  hostPath:
    path: /data/projects