apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitlab-system
 
generatorOptions:
  disableNameSuffixHash: true
 
secretGenerator:
  # - name: awx-secret-tls
  #   type: kubernetes.io/tls
  #   files:
  #     - tls.crt
  #     - tls.key
 
  # - name: secret-awx-postgres
  #   type: Opaque
  #   literals:
  #     - host=awx-postgres
  #     - port=5432
  #     - database=awx
  #     - username=awx
  #     - password=awx-123
  #     - type=managed
 
  # - name: secret-awx-admin
  #   type: Opaque
  #   literals:
  #     - password=awx-123
 
resources:
  - codes/mygitlab.yml
  # - pvc.yml