# L7LBサービス（公開するにあたってのLBとして考える）
apiVersion: networking.k8s.io/v1 
kind: Ingress
# Ingressのメタデータ
metadata:
  namespace: swagger-apps
  name: swagger-apps-ingress
  annotations:
    # kubernetes.io/ingress.class: nginx
    # 正規表現使う
    nginx.ingress.kubernetes.io/use-regex: "true"
    # 正規表現ブロックを引数で表示(この場合、path:の(.*)が$2に当たる)
    nginx.ingress.kubernetes.io/rewrite-target: /$2
# このIngressの仕様
spec:
  ingressClassName: "nginx"
  # 規則
  rules:
    # ヘッダ（FQDNを指定する）
    # - host: 
    - http:
        paths:
            # 公開するurlパス
          - path: /(swagger-editor)/(.*)
            pathType: Prefix
            backend:
              # つなぎたいサービスの情報
              service:
                name: swagger-editor-service
                port:
                  number: 8001
          - path: /(swagger-ui)/(.*)
            pathType: Prefix
            backend:
              # つなぎたいサービスの情報
              service:
                name: swagger-ui-service
                port:
                  number: 8002
          - path: /(prism)/(.*)
            pathType: Prefix
            backend:
              # つなぎたいサービスの情報
              service:
                name: spotlight-prism-service
                port:
                  number: 8003
