apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: mygitlab
spec:
  chart:
    version: "5.9.3" # https://gitlab.com/gitlab-org/cloud-native/gitlab-operator/-/blob/0.6.3/CHART_VERSIONS
    values:
      certmanager:
        install: true
      global:
        hosts:
          # domain: mygitlab.com # use a real domain here
          domain: mygitlab.com # use a real domain here
          https: false
          externalIP: 192.168.125.201
          gitlab:
            name: gitlab.mygitlab.com
            https: false
        ingress:
          configureCertmanager: false
          provider: nginx
      certmanager-issuer:
        email: ryu.ide@fujimic.com # use your real email address here