apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitlab-helm
 
generatorOptions:
  disableNameSuffixHash: true
 
secretGenerator: 
 
resources:
  - ./codes/namespace.yml
  - ./codes/secret.yml
  - ./codes/pv.yml