apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.test.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: web-front
  name: web-front
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web-front
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.test.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/ap-area: "true"
        io.kompose.service: web-front
    spec:
      containers:
        - image: web-front
          name: mmw-front-redirector
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /MMW-front
              name: mmw-front
      hostname: mmw-front-redirector
      restartPolicy: Always
      volumes:
        - name: mmw-front
          persistentVolumeClaim:
            claimName: mmw-front
status: {}
