apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-awx-projects
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  storageClassName: sc-smb-nas-projects