apiVersion: v1
data:
  password: M21PVWNKZjhyRFlPUlRKZ2Ria3FUM0JnOHJqcGFhR0ZHcTYzYm5UUHc1NWk0Tm5acE1tclFlVzhzako1eDVMeg==
  username: Z2l0bGFiX3Jvb3Q=
kind: Secret
metadata:
  creationTimestamp: "2022-06-28T01:18:47Z"
  name: gitlab-root.gitlab-postgres.credentials.postgresql.acid.zalan.do
  namespace: z-postgres
  resourceVersion: "3092790"
type: Opaque
