apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: ap-area
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.kompose.network/ap-area: "true"
  podSelector:
    matchLabels:
      io.kompose.network/ap-area: "true"
