apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitlab-helm
 
generatorOptions:
  disableNameSuffixHash: true
 
secretGenerator: 
 
resources:
  - ./codes/db_secret.yml
  - ./codes/bucket_secrets.yml
  - ./codes/pvc.yml
  # - ./codes/obc-gitlabs.yaml
  # - ./codes/namespace.yml
  # - ./codes/pv.yml