---
version: 1
 
build_arg_defaults:
  # EE_BASE_IMAGE: quay.io/ansible/ansible-runner:latest
  # EE_BASE_IMAGE: quay.io/ansible/ansible-ee:latest
  # EE_BUILDER_IMAGE: quay.io/ansible/ansible-builder:latest
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: --ignore-cert
 
# ansible_config: ansible.cfg
 
dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  # system: bindep.txt
 
additional_build_steps:
  prepend:
    # - RUN whoami
    # - RUN cat /etc/os-release
    # - COPY *crt /etc/pki/ca-trust/source/anchors
    - RUN update-ca-trust
    - ENV http_proxy=http://proxy1.is.fujimic.com:8080
    - ENV https_proxy=http://proxy1.is.fujimic.com:8080
    - ENV HTTP_PROXY=http://proxy1.is.fujimic.com:8080
    - ENV HTTPS_PROXY=http://proxy1.is.fujimic.com:8080
    - ENV proxy=http://proxy1.is.fujimic.com:8080
  append:
    # - RUN echo This is a post-install command!
    # - RUN ls -la /etc