# ingressのサービス化（とりあえず）
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-service
  namespace: ingress-nginx
spec:
  ports:
  - name: http
    nodePort: 30080
    port: 80
    # appProtocol: http
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 30443
    port: 443
    # appProtocol: https
    protocol: TCP
    targetPort: 443
  selector:
    app: ingress-nginx
    # app.kubernetes.io/component: controller
    # app.kubernetes.io/instance: ingress-nginx
    # app.kubernetes.io/name: ingress-nginx
    # app.kubernetes.io/version: 0.49.3
  type: NodePort
  # externalIPs:
  #   - 192.168.125.10
  #   - 192.168.125.11